config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV['HOST']

  devise_for :teachers
  devise_for :students

  mount_griddler('inbound/sendgrid')

  root to: "dashboard#index"

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'inbox', to: 'dashboard#index'
  get 'class', to: 'dashboard#index'
  get 'form', to: 'dashboard#index'
  get 'settings', to: 'dashboard#index'


  get 'api/dashboard'
  get 'api/inbox'

  get 'api/classes/:class_id/students/:student_id/messages', to: 'api#messages'
  post 'api/classes/:class_id/students/:student_id/messages', to: 'api#messages_new'

  get 'api/settings', to: 'api#settings'
  put 'api/settings/info', to: 'api#settings_update_info'
  put 'api/settings/password', to: 'api#settings_update_password'

  
  # Class Page
  get 'api/class', to: 'api#students'
  post 'api/class', to: 'api#add_class'
  delete 'api/class/:class_id', to: 'api#delete_class'
  post 'api/class/upload_list', to: 'api#upload_student_list'

  # Form Page
  get 'api/form',                     to: 'api#form'
  put 'api/form/title',               to: 'api#form_update_title'
  put 'api/form/question',            to: 'api#form_update_question' # change to patch
  put 'api/form/colors',              to: 'api#form_update_colors'
  delete 'api/form/question/:number', to: 'api#form_delete_question'
  post 'api/form/publish',            to: 'api#form_publish'
  post 'api/form/unpublish',          to: 'api#form_unpublish'
  post 'api/form/replicate',          to: 'api#form_replicate'

  get 'student-portal', to: 'student_portal#index', as: 'student_portal'
  get 'student-portal/classes', to: 'student_portal#classes', as: 'student_portal_classes'
  get 'student-portal/subject', to: 'student_portal#subject', as: 'student_portal_subject'
  post 'student-portal/submit', to: 'student_portal#submit', as: 'student_portal_submit'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/student_portal_controller.rb
class StudentPortalController < ApplicationController
  layout 'students'
  before_action :authenticate_student!

  def index
    classes
  end

  def classes
    edu_classes = current_student.edu_classes.all
    @class_list = []
    edu_classes.each do |c|
      form = c.feedback_form
      if form.is_published
        if current_student.feedback_entries.where(feedback_form_id: form.id, date_start: Time.zone.now.strftime(FeedbackEntry::DATE_START_FORMAT)).count == 0
          @class_list.push(id: c.id, name: c.feedback_form.title)
        end
      end
    end
  end

  def subject
    edu_class = current_student.edu_classes.where(id: params[:id]).first
    unless edu_class.nil?
      @form = edu_class.feedback_form
    end
  end

  def submit
    feedback_entry = FeedbackEntry.new(student_id: current_student.id,
                     feedback_form_id: params[:form_id])

    unless params[:question1].blank?
      feedback_entry.question1 = params[:question1]
      feedback_entry.question_score1 = params[:question1].to_i
    end

    unless params[:question2].blank?
      feedback_entry.question2 = params[:question2]
      feedback_entry.question_score2 = params[:question2].to_i
    end

    unless params[:question3].blank?
      feedback_entry.question3 = params[:question3]
      feedback_entry.question_score3 = params[:question3].to_i
    end
    unless params[:question4].blank?
      feedback_entry.question4 = params[:question4]
      feedback_entry.question_score4 = params[:question4].to_i
    end
    unless params[:question5].blank?
      feedback_entry.question5 = params[:question5]
      feedback_entry.question_score5 = params[:question5].to_i
    end

    if feedback_entry.save
      render json: { success: true }
    else
      render json: { success: false, error: feedback_entry.errors.full_messages.join('. ') }
    end

  end
end

app/views/student_portal/index.html.erb
<h2 class="ui header" v-bind:style="{ color: colors.question }">{{headerText}}</h2>

<div v-show="currentPage === 0" style="margin-top: 10px;">
  <div v-for="subject in subjects">
    <button class="ui right massive button form-choice" @click="selectSubject(subject.id)">
      {{ subject.name }}
    </button>
  </div>
  <div v-show="subjects.length === 0">
    No forms
  </div>

  <br>
  <br>
  
  <%= link_to('Logout', destroy_student_session_path, method: :delete, class: 'ui massive button logout' ) %>  

</div>

<div v-show="currentQuestionType === 1">
  <div class="column score-options">
    <br>
    <span class="hide" v-bind:style="{ color: colors.helpText }">Very Unsatisfactory</span>
    <button class="ui icon massive button score"
            v-for="n in currentQuestionSteps"
            v-bind:style="{ backgroundColor: colors.buttonBackground, color: colors.buttonText }"
            @click="selectOption(n)">{{n}}</button>
    <span class="hide" v-bind:style="{ color: colors.helpText }">Very Satisfactory</span>
  </div>
</div>

<div v-show="currentQuestionType === 2">
  <div v-bind:style="{ color: colors.helpText }">{{helperText}}</div>
  <div class="ui segment">
    <div class="ui top attached indicating progress">
      <div class="bar"></div>
    </div>
    <textarea maxlength="4000" rows="5" v-model="responses[currentQuestionIndex]" @keyup.space="updateProgress" @keyup.enter="updateProgress" @keyup.delete="updateProgress"></textarea>
  </div>
</div>

<div v-show="currentQuestionType === 3">
  <div class="column score-options">
    <br>
    <button class="ui icon massive button" 
            v-for="option in currentQuestionOptions"
            v-bind:style="{ backgroundColor: colors.buttonBackground, color: colors.buttonText }" 
            @click="selectOption(option)">{{option}}</button>
  </div>
</div>

<br><br>

<button class="ui big button previous" v-show="currentPage > 1" v-bind:style="{ backgroundColor: colors.buttonBackground, color: colors.buttonText }" @click="prevPage">Previous</button>
<button class="ui big button" v-show="currentQuestionType == 2" v-bind:style="{ backgroundColor: colors.buttonBackground, color: colors.buttonText }" @click="nextPage">Next</button>

<script>

var app = new Vue({
  el: '#app',
  data: {
    studentName: '<%= current_student.name %>',
    subjects: <%= raw @class_list.to_json %>,
    colors: {},

    questions: [],
    responses: [
      '',
      '',
      '',
      '',
      '',
    ],

    currentFormId: 0,
    currentPage: 0,
    helperText: '',
    helperTexts: ['Think carefully. A good answer should be specific',
                  'Please provide more details or give an example to support your feedback',
                  ''],
    disallowNext: false,
  },
  methods: {
    selectSubject: function(id) {
      $.get( '<%= student_portal_subject_path %>', { id: id }, function(data) {
        this.currentFormId = data.id;
        this.colors = data.colors;
        this.questions = data.questions;

        this.nextPage();
      }.bind(this));
    },

    selectOption: function(option) {
      this.responses[this.currentQuestionIndex] = option;
      this.nextPage();
    },

    prevPage: function() {
      this.currentPage--;

      if (this.currentPage < 1) {
        this.currentPage = 1;
      }

      // for free response text
      if (this.currentQuestionType === 2) {
        this.updateProgress();
      }
      
      $(window).scrollTop(0);
    },

    nextPage: function() {
      if (this.currentQuestionType === 2) {
        this.updateProgress(); // update again to check latest
        if (this.disallowNext) {
          alert('Please share more details.');
          return;
        }
      }

      if (this.currentPage >= this.questions.length) {
        this.submitForm();
      } else {
        this.currentPage++;

        // for free response text
        if (this.currentQuestionType === 2) {
          this.updateProgress();
        }
      }
      $(window).scrollTop(0);
    },
    submitForm: function() {
      $.post('<%= student_portal_submit_path %>', {
        form_id: this.currentFormId,
        question1: this.responses[0],
        question2: this.responses[1],
        question3: this.responses[2],
        question4: this.responses[3],
        question5: this.responses[4],
      }).done(function( data ) {
        if (data.success) {
          alert('Form submitted.');
          this.gotoHome();
        } else {
          alert(data.error);
        }
      }.bind(this));
    },
    updateProgress: function() {
      if (this.currentQuestionType === 1) {
        this.disallowNext = false;
        return;
      }
      if (this.responses[this.currentQuestionIndex].length === 0) {
        wordCount = 0;
      } else {
        wordCount = this.responses[this.currentQuestionIndex].split(' ').length;
      }
      percent = wordCount * 12.5;

      if (wordCount >= 0 && wordCount <=2) {
        this.helperText = this.helperTexts[0];
      } else if (wordCount >= 3 && wordCount <= 7) {
        this.helperText = this.helperTexts[1];
      } else {
        this.helperText = this.helperTexts[2];
      }
      percent = percent > 100 ? 100 : percent;
      $('.top.progress').progress({percent: percent});

      this.disallowNext = percent != 100;
    },
    gotoHome: function() {
      // add loading icon

      $.get( '<%= student_portal_classes_path %>', function(data) {
        this.subjects = data.classes;

        this.currentPage = 0;

        // clear form data
        this.responses = [ '', '', '', '', '' ];
      }.bind(this));
    }
  },
  computed: {
    headerText() {
      if (this.currentPage === 0) {
        return 'Welcome ' + this.studentName;
      } else if (this.currentQuestionIndex < this.questions.length) {
        return this.questions[this.currentQuestionIndex].text;
      } else {
        return '';
      }
    },
    currentQuestionIndex() {
      return this.currentPage - 1;
    },
    currentQuestionType() {
      if (this.currentPage <= 0) {
        return -1;
      } else if (this.currentQuestionIndex < this.questions.length) {
        return this.questions[this.currentQuestionIndex].type;
      } else {
        return '';
      }
    },
    currentQuestionSteps() {
      if (this.currentQuestionIndex >= 0 &&
          this.currentQuestionIndex < this.questions.length && 
          this.questions[this.currentQuestionIndex].data !== null && 
          this.questions[this.currentQuestionIndex].data.steps !== undefined) {
        return this.questions[this.currentQuestionIndex].data.steps;
      } else {
        return 0;
      }
    },
    currentQuestionOptions() {
      if (this.currentQuestionIndex >= 0 &&
          this.currentQuestionIndex < this.questions.length && 
          this.questions[this.currentQuestionIndex].data !== null && 
          this.questions[this.currentQuestionIndex].data.options !== undefined) {
        return this.questions[this.currentQuestionIndex].data.options;
      } else {
        return [];
      }
    },
  },
});

</script>