config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV['HOST']

  devise_for :teachers
  devise_for :students

  mount_griddler('inbound/sendgrid')

  root to: "dashboard#index"

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'inbox', to: 'dashboard#index'
  get 'class', to: 'dashboard#index'
  get 'form', to: 'dashboard#index'
  get 'settings', to: 'dashboard#index'


  get 'api/dashboard'
  get 'api/inbox'

  get 'api/classes/:class_id/students/:student_id/messages', to: 'api#messages'
  post 'api/classes/:class_id/students/:student_id/messages', to: 'api#messages_new'

  get 'api/settings', to: 'api#settings'
  put 'api/settings/info', to: 'api#settings_update_info'
  put 'api/settings/password', to: 'api#settings_update_password'

  
  # Class Page
  get 'api/class', to: 'api#students'
  post 'api/class', to: 'api#add_class'
  delete 'api/class/:class_id', to: 'api#delete_class'
  post 'api/class/upload_list', to: 'api#upload_student_list'

  # Form Page
  get 'api/form',                     to: 'api#form'
  put 'api/form/title',               to: 'api#form_update_title'
  put 'api/form/question',            to: 'api#form_update_question' # change to patch
  put 'api/form/colors',              to: 'api#form_update_colors'
  delete 'api/form/question/:number', to: 'api#form_delete_question'
  post 'api/form/publish',            to: 'api#form_publish'
  post 'api/form/unpublish',          to: 'api#form_unpublish'
  post 'api/form/replicate',          to: 'api#form_replicate'

  get 'student-portal', to: 'student_portal#index', as: 'student_portal'
  get 'student-portal/classes', to: 'student_portal#classes', as: 'student_portal_classes'
  get 'student-portal/subject', to: 'student_portal#subject', as: 'student_portal_subject'
  post 'student-portal/submit', to: 'student_portal#submit', as: 'student_portal_submit'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduPulse</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <script> 
    var $buoop = {vs:{i:8,f:-4,o:-4,s:8,c:-4},mobile:false,api:4}; 
    function $buo_f(){ 
     var e = document.createElement("script"); 
     e.src = "//browser-update.org/update.min.js"; 
     document.body.appendChild(e);
    };
    try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
    catch(e){window.attachEvent("onload", $buo_f)}
    </script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduPulse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="form">
      <ul class="tab-group">
        <li class="tab<%= if current_page?(new_teacher_registration_path) then ' active' end %>">
          <a href="<%= new_teacher_registration_path %>">Sign Up</a>
        </li>
        <li class="tab<%= if current_page?(new_teacher_session_path) || current_page?(new_teacher_password_path) then ' active' end %>">
          <a href="<%= new_teacher_session_path %>">Log In</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="signup">   
          <% if !notice.blank? %>
            <h1 class="notice"><%= notice %></h1>
          <% elsif !alert.blank? %>
            <h1 style="color: #c0392b;"><%= alert %></h1>
          <% else %>
            <% if current_page?(new_teacher_session_path) %>
              <h1>Welcome Back!</h1>
            <% elsif current_page?(new_teacher_registration_path) %>
              <h1>Sign Up for Free</h1>
            <% elsif current_page?(new_teacher_password_path) %>
              <h1>Send Me Reset Password Instructions</h1>
            <% end %>
          <% end %>
          <%= yield %>
        </div>
      </div><!-- tab-content -->
    </div> <!-- /form -->


    <script> 
    var $buoop = {vs:{i:8,f:-4,o:-4,s:8,c:-4},mobile:false,api:4}; 
    function $buo_f(){ 
     var e = document.createElement("script"); 
     e.src = "//browser-update.org/update.min.js"; 
     document.body.appendChild(e);
    };
    try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
    catch(e){window.attachEvent("onload", $buo_f)}
    </script>

    <script>
    $(function() {
      $('.form').find('input[type="email"], input[type="password"]').on('keyup blur focus', function (e) {
        var $this = $(this),
        label = $this.prev('label');
        if ($this.val() === '') {
          label.removeClass('hide');
        } else {
          label.addClass('hide');
        }
      });

      $('.form').find('input[type="email"], type[type="password"]').each(function () {
               var $this = $(this),
        label = $this.prev('label');
        if ($this.val() === '') {
          label.removeClass('hide');
        } else {
          label.addClass('hide');
        } 
      });

    });
    </script>


<style>
*, *:before, *:after {
  box-sizing: border-box;
}

html {
  overflow-y: scroll;
}

body {
  background: #c1bdba;
  font-family: 'Titillium Web', sans-serif;
}

a {
  text-decoration: none;
  color: #1ab188;
  -webkit-transition: .5s ease;
  transition: .5s ease;
}
a:hover {
  color: #179b77;
}

.form {
  background: rgba(19, 35, 47, 0.9);
  padding: 40px;
  max-width: 600px;
  margin: 40px auto;
  border-radius: 4px;
  box-shadow: 0 4px 10px 4px rgba(19, 35, 47, 0.3);
}

.tab-group {
  list-style: none;
  padding: 0;
  margin: 0 0 40px 0;
}
.tab-group:after {
  content: "";
  display: table;
  clear: both;
}
.tab-group li a {
  display: block;
  text-decoration: none;
  padding: 15px;
  background: rgba(160, 179, 176, 0.25);
  color: #a0b3b0;
  font-size: 20px;
  float: left;
  width: 50%;
  text-align: center;
  cursor: pointer;
  -webkit-transition: .5s ease;
  transition: .5s ease;
}
.tab-group li a:hover {
  background: #179b77;
  color: #ffffff;
}
.tab-group .active a {
  background: #1ab188;
  color: #ffffff;
}

h1 {
  text-align: center;
  color: #ffffff;
  font-weight: 300;
  margin: 0 0 40px;
}

label {
  position: absolute;
  -webkit-transform: translateY(6px);
          transform: translateY(6px);
  left: 13px;
  color: rgba(255, 255, 255, 0.5);
  -webkit-transition: all 0.25s ease;
  transition: all 0.25s ease;
  -webkit-backface-visibility: hidden;
  pointer-events: none;
  font-size: 22px;
}
label .req {
  margin: 2px;
  color: #1ab188;
}

label.active {
  -webkit-transform: translateY(50px);
          transform: translateY(50px);
  left: 2px;
  font-size: 14px;
}
label.active .req {
  opacity: 0;
}

label.highlight {
  color: #ffffff;
}

input, textarea {
  font-size: 22px;
  display: block;
  width: 100%;
  height: 100%;
  padding: 5px 10px;
  background: none;
  background-image: none;
  border: 1px solid #a0b3b0;
  color: #ffffff;
  border-radius: 0;
  -webkit-transition: border-color .25s ease, box-shadow .25s ease;
  transition: border-color .25s ease, box-shadow .25s ease;
}
input:focus, textarea:focus {
  outline: 0;
  border-color: #1ab188;
}

textarea {
  border: 2px solid #a0b3b0;
  resize: vertical;
}

.field-wrap {
  position: relative;
  margin-bottom: 40px;
}

.top-row:after {
  content: "";
  display: table;
  clear: both;
}
.top-row > div {
  float: left;
  width: 48%;
  margin-right: 4%;
}
.top-row > div:last-child {
  margin: 0;
}



input[type=submit] {
  border: 0;
  outline: none;
  border-radius: 0;
  padding: 15px 0;
  font-size: 2rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: .1em;
  background: #1ab188;
  color: #ffffff;
  -webkit-transition: all 0.5s ease;
  transition: all 0.5s ease;
  -webkit-appearance: none;
}
input[type=submit]:hover, input[type=submit]:focus {
  background: #179b77;
}

input[type=submit] {
  display: block;
  width: 100%;
}

.forgot {
  margin-top: -20px;
  text-align: right;
}
</style>


  </body>
</html>

app/views/layouts/students.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduPulse</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="ui form students" id="app" style="min-height: 500px;">
        <div class="ui container">
          <div class="ui center aligned segment">
            <% unless alert.nil? %>
              <p class="alert"><%= alert %></p>
            <% end %>

            <%= yield %>
        </div>
      </div>
    </div>

<style>
  body{ background: linear-gradient(45deg, #ff5c5c 0%, rgba(152, 44, 129, 0.86) 100%); }
</style>

  </body>
</html>